### ISSUE TITLE
Add an example on how to use the font

### ISSUE THREAD

**Issue by phocean** [ericcornelissen/jekyll-fontello#1]
Hi,

It would be nice to have at least an example on how to use the font.
For non developers, it's not obvious at all.

**Comment by ericcornelissen** [comment]
Apologies for the delay, care to help me out in understanding what is not obvious? Which of the following steps are you having trouble with (or maybe something else)?

1. Install the plugin
1. Add a fontello configuration file
1. Configure the plugin in `_config.yml`
1. Use fontello in your project.

**Comment by phocean** [comment]
Mostly step 4, the rest looks rather trivial to me.

**Comment by ericcornelissen** [comment]
I tried to modify the installation guidelines in the README as shown below ⬇️ What do you think, is that a step in the right direction? Remember that in the installation guidelines I assume no custom configuration is used.

A few things I'm doubting.

- Is it clear how to add the CSS file to your pages? The difficulty with this is that it depends on how you're using Jekyll...
- Fontello actually generates multiple CSS files (e.g. one specifically to support Internet Explorer 7), but for simplicity I only show you need to add the one most people will use.
- The class name in step 5 depends on the Fontello configuration, I think this should be clear to people using Fontello but I'm still not 100% about it.

---

## Installation

1. Install the `jekyll-fontello` gem:
```shell
$ gem install jekyll-fontello
```
2. Add `jekyll-fontello` to the list of plugins in `_config.yml`:
```yaml
plugins:
  - jekyll-fontello
```
3. Add a Fontello configuration file named `fontello_config.json` to your project.
4. Include the Fontello `.css` file in your pages.
```html
<link href="/fontello/styles/fontello.css" rel="stylesheet" type="text/css">
```
5. Use Fontello icons on your website or blog!
```html
<i class="icon-rocket">
```

_Or_ copy `lib/jekyll-fontello.rb` into your `_plugins` directory.

**Comment by phocean** [comment]
It looks perfect, clear and complete to my understanding.
With this, I can't fail to use it.
Many thanks for the time you took for this improvement! Very much appreciated :-)

**Comment by ericcornelissen** [comment]
Thanks for the feedback, I updated the text in the README 👍
